print("I hope this finally works")
animal = input ("Name an animal:")
print ("This is a",animal,)
car = input("Whats your favourite car?")
print("Mr.Ben really like this",car,)
print ("FINALLY IT HAS WORKED NOW I CAN START SAVING MY WORK ON GITHUB!")