print("Random questions with asnwers")
animal = input ("Name an animal:")
print ("Hmm you choose",animal,"Not a bad choice")
car = input("Whats your favourite car:")
print("Mr.Ben really like this",car,"too")
print ("FINALLY IT HAS WORKED NOW I CAN START SAVING MY WORK ON GITHUB!") 
print("This time its me Nicole") 
